### ISSUE TITLE
라이브러리를 불러오는 과정에서 몇 가지 오류가 발생합니다.

### ISSUE THREAD

**Issue by needleworm** [elbakramer/koapy#10]
안녕하세요, 좋은 패키지를 공개해 주셔서 감사합니다.

Koapy를 사용하려고 예제 코드를 시도했습니다만, 패키지를 불러오는 과정에서 오류가 발생했습니다.

from koapy import KiwoomOpenApiContext
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\__init__.py", line 10, in <module>
    from koapy.context.KiwoomOpenApiContext import KiwoomOpenApiContext
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\context\KiwoomOpenApiContext.py", line 5, in <module>
    from koapy.grpc.KiwoomOpenApiServiceClient import KiwoomOpenApiServiceClient
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\grpc\KiwoomOpenApiServiceClient.py", line 4, in <module>
    from koapy.grpc.KiwoomOpenApiServiceClientStubWrapper import KiwoomOpenApiServiceClientStubWrapper
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\grpc\KiwoomOpenApiServiceClientStubWrapper.py", line 11, in <module>
    from koapy.openapi.RealType import RealType
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\openapi\RealType.py", line 168, in <module>
    RealType.load_from_dump_file()
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\openapi\RealType.py", line 164, in load_from_dump_file
    cls.Fid.load_from_dump_file()
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\openapi\RealType.py", line 39, in load_from_dump_file
    cls._NAME_BY_FID = cls.name_by_fid_from_dump_file(dump_file)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\openapi\RealType.py", line 32, in name_by_fid_from_dump_file
    df = pd.read_excel(dump_file)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\pandas\util\_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\pandas\io\excel\_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\pandas\io\excel\_base.py", line 1102, in __init__
    raise ValueError(
ValueError: Your version of xlrd is 2.0.1. In xlrd >= 2.0, only the xls format is supported. Install openpyxl instead.

위 문제는 xlrd를 1.2.0 버전으로 다운그레드하니 실행은 됩니다만 추가적으로 아래와 같은 Warning이 발생합니다.

FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  df = pd.read_excel(dump_file)

확인 부탁드립니다, 감사합니다 :)

**Comment by elbakramer** [comment]
안녕하세요. 리포트 감사합니다.

저도 내부적으로는 공유주신 것처럼 엑셀파일 처리와 관련한 의존성 이슈를 발견했었구요.
최신 개발 버전상으로는 기존 `xlrd` 에서 `openpyxl` 로 변경하는것을 검토해서 수정했었지만
이것을 따로 릴리즈를 하거나 하진 않았었습니다.

그러다 최근에 전체적인 코드 구조를 개편하면서 관련 내용도 수정이된 릴리즈 버전이 나왔는데요. (`v0.3.2`)
이쪽으로 한번 버전 업데이트 후 테스트 해보시기 바랍니다.

**Comment by elbakramer** [comment]
관련 문제들이 최근 버전에서는 더이상 없을 것으로 생각해서 이슈 닫습니다.
기존 `from koapy import KiwoomOpenApiContext` 구문이 최근 버전에서는 `from koapy import KiwoomOpenApiPlusEntrypoint` 로 대응되도록 바뀌었으니 참고 바랍니다.
