### ISSUE TITLE
'KiwoomOpenApiPlusEntrypoint' object has no attribute '_client'

### ISSUE THREAD

**Issue by ooodragon94** [elbakramer/koapy#115]
완전히 새로운 환경에서 아무리 시도를 해도 위의 에러가 뜹니다
python 3.10버전으로 시도중입니다.

   self._server_executable = get_32bit_executable()
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\config.py", line 303, in get_32bit_executable
    return get_executable_from_executable_config(executable_config)
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\config.py", line 289, in get_executable_from_executable_config
    return get_executable_from_conda_envname(envname)
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\config.py", line 248, in get_executable_from_conda_envname
    return subprocess.check_output(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
Exception ignored in: <function KiwoomOpenApiPlusEntrypoint.__del__ at 0x000002CB70B6C790>
Traceback (most recent call last):
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\backend\kiwoom_open_api_plus\core\KiwoomOpenApiPlusEntrypoint.py", line 62, in __del__
    self.close()
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\backend\kiwoom_open_api_plus\core\KiwoomOpenApiPlusEntrypoint.py", line 89, in close
    self.close_client()
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\backend\kiwoom_open_api_plus\core\KiwoomOpenApiPlusEntrypoint.py", line 80, in close_client
    self._client.close()
  File "C:\Users\$user$\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\koapy\backend\kiwoom_open_api_plus\core\KiwoomOpenApiPlusEntrypoint.py", line 96, in __getattr__
    return self.__getattribute__(name)
AttributeError: 'KiwoomOpenApiPlusEntrypoint' object has no attribute '_client'

**Comment by ooodragon94** [comment]
installation 방법이 document에 있었군요.
감사합니다.
